server:
  port: 8081
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: luoboyu_route
          uri: http://www.jd.com/
          predicates:
            - Path=/jd
        - id: query_route
          uri: http://www.tuhu.cn
          predicates:
          - Query=method
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG